apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    name: blog
  name: blog
spec:
  serviceName: blog
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      name: blog
  template:
    metadata:
      name: blog
      labels:
        name: blog
    spec:
      containers:
      - image: ghost:4.8.4
        name: blog
        env:
        - name: database__client
          value:  mysql
        - name: database__connection__host
          value: blog-db
        - name: database__connection__user
          valueFrom:
            secretKeyRef:
              name: db-account-secret
              key: username
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name: db-account-secret
              key: password
        - name: database__connection__database
          valueFrom:
            secretKeyRef:
              name: db-account-secret
              key: dbName
        - name: url
          value: https://home-labs.me
        - name: CUSTOM_ENV
          value: "Hello Argocd"
        - name: CUSTOM_ENV_2
          value: "Hello Argocd, hi "
        ports:
        - containerPort: 2368
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        volumeMounts:
        - name: blog-app-pv
          mountPath: /var/lib/ghost/content
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      volumes:
      - name: blog-app-pv
        persistentVolumeClaim:
          claimName: blog-app-pv-claim
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
