apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blog-db
  namespace: staging
spec:
  selector:
    matchLabels:
      app: blog-db
  serviceName: blog-db
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: blog-db
    spec:
      containers:
      - image: mysql:5.7.35
        args:
          - "--explicit_defaults_for_timestamp"
        name: blog-db
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-account-secret
              key: rootPassword
        - name: MYSQL_USER 
          valueFrom:
            secretKeyRef:
              name: db-account-secret
              key: username
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-account-secret
              key: dbName
        - name: MYSQL_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: db-account-secret
              key: password
        ports:
        - containerPort: 3306
          name: blog-db
        volumeMounts:
        - name: blog-db-pv
          mountPath: /var/lib/mysql
      volumes:
      - name: blog-db-pv
        persistentVolumeClaim:
          claimName: blog-db-pv-claim

