apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: blog
  name: blog
  namespace: staging
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: blog
  template:
    metadata:
      name: blog
      labels:
        name: blog
    spec:
      containers:
      - image: ghost:3.42.5
        name: blog
        env:
        - name: database__client
          value:  mysql
        - name: database__connection__host
          value: blog-db.staging
        - name: database__connection__user
          valueFrom:
            secretKeyRef:
              name: db-account-secret
              key: username
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name: db-account-secret
              key: password
        - name: database__connection__database
          valueFrom:
            secretKeyRef:
              name: db-account-secret
              key: dbName
        - name: url
          value: http://159.89.211.147:2368
        - name: CUSTOM_ENV
          value: "Hello Argocd"
        - name: CUSTOM_ENV_2
          value: "Hello Argocd, My Name is Tien"
        ports:
        - containerPort: 2368
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
