apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: blog
  name: blog
  namespace: staging
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: blog
  template:
    metadata:
      name: blog
      labels:
        name: blog
    spec:
      containers:
      - image: ghost:4.2.1
        name: blog
        env:
        - name: database__client
          value:  mysql
        - name: database__connection__host
          value: blog-db
        - name: database__connection__user
          value: root
        - name: database__connection__password
          value: fcf60a10c7883e364a4abba570b4655dabf99abbb061f765
        - name: database__connection__database
          value: ghost
        - name: url
          value: https://tosu-thien.com
        ports:
        - containerPort: 2368
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
