apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ingress
spec:
  tls:
  - hosts:
    - home-labs.me
    secretName: hsc-secret
  rules:
  - host: home-labs.me
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blog
            port:
              number: 2368
